name: panacea
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy>=1.22,<2.0
  - scipy>=1.8
  - astropy>=5,<6
  - matplotlib>=3.5
  - pyyaml>=6.0
  - tqdm>=4.60
  - requests
  - scikit-learn
  - pip
  - pip:
    - linkify-it-py>=2
    - ruff==0.14.11
    - -e .
